// app/data.ts
import { Property, Project } from "./type";

export const properties: Property[] = [
  {
    id: 1,
    title: "Premium Agricultural Land near Ujjain ",
    slug: "premium-agricultural-land-ujjain",
    type: "agriculture",
    location: "Mundli, Madhya Pradesh",
    price: "₹14 Cr",
    area: "20 Beegha",
    coordinates: { lat: 23.309621576120946, lng: 76.0460891580918 },
    image: "/grass/Mundli_zameen.png",
    features: [
      "Available in parcels of 5 Beegha",
      "Fertile Soil",
      "Water Access",
      "Own a Well",
      "Highway Access",
      "Investment Ready",
    ],
    rating: 4.8,
    views: 234,
    description:
      "Excellent agricultural land with rich black soil, perfect for crop cultivation. Well-connected by road with water facility available.",
    verified: true,
    projectSlug: "",
  },
  {
    id: 2,
    title: "Commercial Office Space in Indore",
    slug: "commercial-office-space-indore",
    type: "commercial",
    location: "Indore, Madhya Pradesh",
    price: "Call for Price",
    area: "520 sq ft",
    coordinates: { lat: 22.6775, lng: 75.8417 },
    image: "/grass/residence.png",
    features: [
      "Main Road",
      "High Footfall",
      "Commercial Zone",
      "Investment Ready",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime commercial plot located on main road with excellent visibility and high footfall area. Perfect for retail or office space.",
    verified: true,
    projectSlug: "arna-residency",
  },
  {
    id: 3,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1407-1",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹81 lakhs",
    area: "1407 sq ft",
    coordinates: { lat: 22.6775, lng: 75.8417 },
    image: "/grass/residence.png",
    features: [
      "Choithram School 6 mins away",
      "Choithram Hospital 6 mins away",
      "Vegetable/Fruits Market(Main Mandi) 2 mins away",
      "Parking space available",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment has a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 9'4\") leads into a combined Drawing and Dining area, which measures 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with a separate Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") accessible from the drawing room.",
          ],
        },
        {
          title: "Bedrooms & Bathrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached Toilet (4'0\" x 6'8\") and a private Balcony (4'4\" x 3'4\").",
            "Bedroom 2: (11'0\" x 10'0\") with an attached Toilet (9'8\" x 5'0\").",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
            "In total, the apartment has three bedrooms, three attached toilets, and one common toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "arna-residency",
  },
  {
    id: 4,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1407-2",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹81 lakhs",
    area: "1407 sq ft",
    coordinates: { lat: 22.6774, lng: 75.8415 },
    image: "/grass/residence.png",
    features: [
      "Choithram School 6 mins away",
      "Choithram Hospital 6 mins away",
      "Vegetable/Fruits Market(Main Mandi) 2 mins away",
      "Parking space available",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment has a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 9'4\") leads into a combined Drawing and Dining area, which measures 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with a separate Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") accessible from the drawing room.",
          ],
        },
        {
          title: "Bedrooms & Bathrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached Toilet (4'0\" x 6'8\") and a private Balcony (4'4\" x 3'4\").",
            "Bedroom 2: (11'0\" x 10'0\") with an attached Toilet (9'8\" x 5'0\").",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
            "In total, the apartment has three bedrooms, three attached toilets, and one common toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "arna-residency",
  },
  {
    id: 5,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1302-1",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹78 lakhs",
    area: "1302 sq ft",
    coordinates: { lat: 22.6776, lng: 75.8415 },
    image: "/grass/residence.png",
    features: [
      "Choithram School 6 mins away",
      "Choithram Hospital 6 mins away",
      "Vegetable/Fruits Market(Main Mandi) 2 mins away",
      "Parking space available",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment features a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 7'0\") leads into a spacious combined Drawing and Dining area, measuring an impressive 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with an attached Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") located next to the kitchen.",
          ],
        },
        {
          title: "Bedrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached toilet and private balcony.",
            "Bedroom 2: (11'0\" x 10'0\") with an attached toilet.",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "arna-residency",
  },
  {
    id: 6,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1302-2",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹78 lakhs",
    area: "1302 sq ft",
    coordinates: { lat: 22.6776, lng: 75.8416 },
    image: "/grass/residence.png",
    features: [
      "Choithram School 6 mins away",
      "Choithram Hospital 6 mins away",
      "Vegetable/Fruits Market(Main Mandi) 2 mins away",
      "Parking space available",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment features a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 7'0\") leads into a spacious combined Drawing and Dining area, measuring an impressive 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with an attached Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") located next to the kitchen.",
          ],
        },
        {
          title: "Bedrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached toilet and private balcony.",
            "Bedroom 2: (11'0\" x 10'0\") with an attached toilet.",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "arna-residency",
  },
  {
    id: 7,
    title: "Commercial Office/Shop in Indore",
    slug: "commercial-office-space-indore",
    type: "commercial",
    location: "Indore, Madhya Pradesh",
    price: "Call for Price",
    area: "520 sq ft",
    coordinates: { lat: 22.6774, lng: 75.8415 },
    image: "/grass/residence.png",
    features: [
      "Main Road",
      "High Footfall",
      "Commercial Zone",
      "Investment Ready",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime commercial plot located on main road with excellent visibility and high footfall area. Perfect for retail or office space.",
    verified: true,
    projectSlug: "arna-residency",
  },
  {
    id: 8,
    title: "Agricultural Land near NH-52 Bagoda",
    slug: "agricultural-land-Bagoda",
    type: "agriculture",
    location: "Bagoda, Madhya Pradesh",
    price: "₹11.25 cr",
    area: "15 Beegha",
    coordinates: { lat: 23.324043026885096, lng: 76.05202089582649 },
    image: "/grass/bagoda.png",
    features: [
      "Available in parcels of 5 Beegha",
      "Main Road",
      "Highway Access",
      "Commercial Zone",
      "Investment Ready",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime commercial plot located on main road with excellent visibility and high footfall area. Perfect for retail or office space.",
    verified: true,
    projectSlug: "",
  },
  {
    id: 9,
    title: "Agricultural Land on Ujjain-Agar Road",
    slug: "agricultural-land-agar-ujjain-road",
    type: "agriculture",
    location: "Ujjain-Agar Road, Madhya Pradesh",
    price: "₹2.15 cr ",
    area: "18700 sq ft",
    coordinates: { lat: 23.324043026885096, lng: 76.05202089582649 },
    image: "/grass/Ghatiya-road.jpeg",
    features: [
      "Main Road",
      "Highway Access",
      "Commercial Zone",
      "Investment Ready",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime commercial plot located on main road with excellent visibility and high footfall area. Perfect for retail or office space.",
    verified: true,
    projectSlug: "",
  },
];

export const projects: Project[] = [
  {
    id: 1,
    slug: "arna-residency",
    title: "Arna Residency",
    developer: "Project Arna",
    image: "/grass/residence.png",
    images: [],
    description:
      "This premier residential project offers luxurious living spaces with state-of-the-art amenities. Located in a prime area with excellent connectivity, it also provides the added convenience of integrated retail shops for all your daily needs.",
    location: "Indore, Madhya Pradesh",
    status: "Under Construction",
    features: ["RERA Approved", "", "", "24/7 Security"],
    propertyCount: 10,
  },
];
