// app/data.ts
import { Property, Project } from "./type";

export const properties: Property[] = [
  {
    id: 1,
    title: "Premium Agricultural Land near Ujjain ",
    slug: "premium-agricultural-land-ujjain",
    type: "agriculture",
    location: "Mundli, Madhya Pradesh",
    price: "Call for Price",
    area: "20 Beegha",
    coordinates: { lat: 23.309621576120946, lng: 76.0460891580918 },
    image: "/Mundli_zameen.png",
    features: [
      "Available in parcels",
      "Fertile Soil",
      "Water Access",
      "Own a Well",
      "Highway Access",
      "Investment Ready",
    ],
    rating: 4.8,
    views: 234,
    description:
      "Excellent agricultural land with rich black soil, perfect for crop cultivation. Well-connected by road with water facility available.",
    verified: true,
    projectSlug: "",
  },
  {
    id: 2,
    title: "Commercial Office Shops in Indore",
    slug: "commercial-office-shops-indore",
    type: "commercial",
    location: "Indore, Madhya Pradesh",
    price: "Call for Price",
    area: "520 sq ft",
    coordinates: { lat: 22.6775, lng: 75.8417 },
    image: "/residence.png",
    features: [
      "Main Road",
      "High Footfall",
      "Investment Ready",
      "High Ceiling",
      "Parking Available",
      "Capital Appreciation",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime commercial plot located on main road with excellent visibility and high footfall area. Perfect for retail or office space.",
    verified: true,
    projectSlug: "aarna-ssd-enclave",
  },
  {
    id: 3,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1407-1",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹81 lakhs",
    area: "1407 sq ft",
    coordinates: { lat: 22.6775, lng: 75.8417 },
    image: "/1407.JPEG",
    features: [
      "School 6 mins",
      "Hospital 6 mins",
      "Vegetable/Fruits Market",
      "Parking space available",
      "Strong ROI Potential",
      "Lift Access",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment has a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 9'4\") leads into a combined Drawing and Dining area, which measures 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with a separate Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") accessible from the drawing room.",
          ],
        },
        {
          title: "Bedrooms & Bathrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached Toilet (4'0\" x 6'8\") and a private Balcony (4'4\" x 3'4\").",
            "Bedroom 2: (11'0\" x 10'0\") with an attached Toilet (9'8\" x 5'0\").",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
            "In total, the apartment has three bedrooms, three attached toilets, and one common toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "aarna-ssd-enclave",
  },
  {
    id: 4,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1407-2",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹81 lakhs",
    area: "1407 sq ft",
    coordinates: { lat: 22.6774, lng: 75.8415 },
    image: "/1407.JPEG",
    features: [
      "School 6 mins",
      "Hospital 6 mins",
      "Vegetable/Fruits Market",
      "Parking space available",
      "Strong ROI Potential",
      "Lift Access",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment has a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 9'4\") leads into a combined Drawing and Dining area, which measures 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with a separate Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") accessible from the drawing room.",
          ],
        },
        {
          title: "Bedrooms & Bathrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached Toilet (4'0\" x 6'8\") and a private Balcony (4'4\" x 3'4\").",
            "Bedroom 2: (11'0\" x 10'0\") with an attached Toilet (9'8\" x 5'0\").",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
            "In total, the apartment has three bedrooms, three attached toilets, and one common toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "aarna-ssd-enclave",
  },
  {
    id: 5,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1302-1",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹78 lakhs",
    area: "1302 sq ft",
    coordinates: { lat: 22.6776, lng: 75.8415 },
    image: "/1302.png",
    features: [
      "School 6 mins",
      "Hospital 6 mins",
      "Vegetable/Fruits Market",
      "Parking space available",
      "Strong ROI Potential",
      "Lift Access",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment features a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 7'0\") leads into a spacious combined Drawing and Dining area, measuring an impressive 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with an attached Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") located next to the kitchen.",
          ],
        },
        {
          title: "Bedrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached toilet and private balcony.",
            "Bedroom 2: (11'0\" x 10'0\") with an attached toilet.",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "aarna-ssd-enclave",
  },
  {
    id: 6,
    title: "3 BHK House in Indore",
    slug: "3-bhk-house-indore-1302-2",
    type: "residential",
    location: "Indore, Madhya Pradesh",
    price: "₹78 lakhs",
    area: "1302 sq ft",
    coordinates: { lat: 22.6776, lng: 75.8416 },
    image: "/1302.png",
    features: [
      "School 6 mins",
      "Hospital 6 mins",
      "Vegetable/Fruits Market",
      "Parking space available",
      "Strong ROI Potential",
      "Lift Access",
    ],
    rating: 4.9,
    views: 445,
    description: "",
    layout: {
      overview:
        "The apartment features a three-bedroom layout with a central common area. The entrance from the Lobby (9'8\" x 7'0\") leads into a spacious combined Drawing and Dining area, measuring an impressive 25'0\" x 10'0\".",
      sections: [
        {
          title: "Kitchen & Common Areas",
          points: [
            "Kitchen: (8'0\" x 10'0\") with an attached Balcony (5'4\" x 10'0\").",
            "Common Toilet: (4'0\" x 6'8\") located next to the kitchen.",
          ],
        },
        {
          title: "Bedrooms",
          points: [
            "Master Bedroom: (12'0\" x 10'0\") with an attached toilet and private balcony.",
            "Bedroom 2: (11'0\" x 10'0\") with an attached toilet.",
            "Bedroom 3: (9'8\" x 12'0\") with an attached toilet.",
          ],
        },
      ],
    },
    verified: true,
    projectSlug: "aarna-ssd-enclave",
  },
  {
    id: 7,
    title: "Commercial Shop in Indore",
    slug: "commercial-office-shop-indore",
    type: "commercial",
    location: "Indore, Madhya Pradesh",
    price: "Call for Price",
    area: "520 sq ft",
    coordinates: { lat: 22.6774, lng: 75.8415 },
    image: "/residence.png",
    features: [
      "Main Road",
      "High Footfall",
      "Investment Ready",
      "High Ceiling",
      "Parking Available",
      "Capital Appreciation",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime commercial plot located on main road with excellent visibility and high footfall area. Perfect for retail or office space.",
    verified: true,
    projectSlug: "aarna-ssd-enclave",
  },
  {
    id: 8,
    title: "Agricultural Land near NH-52 Bagoda",
    slug: "agricultural-land-Bagoda",
    type: "agriculture",
    location: "Bagoda, Madhya Pradesh",
    price: "Call for Price",
    area: "15 Beegha",
    coordinates: { lat: 23.324043026885096, lng: 76.05202089582649 },
    image: "/bagoda.png",
    features: [
      "Available in parcels",
      "Main Road",
      "Highway Access",
      "Commercial Zone",
      "Investment Ready",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime agriculture plot located on main road with excellent visibility and high footfall area. Perfect for farmhouse and agriculture needs.",
    verified: true,
    projectSlug: "",
  },
  {
    id: 9,
    title: "Agricultural Land on Ujjain-Agar Road",
    slug: "agricultural-land-agar-ujjain-road",
    type: "agriculture",
    location: "Ujjain-Agar Road, Madhya Pradesh",
    price: "Call for Price",
    area: "18700 sq ft",
    coordinates: { lat: 23.324043026885096, lng: 76.05202089582649 },
    image: "/Ghatiya-road.jpeg",
    features: [
      "Main Road",
      "Highway Access",
      "Commercial Zone",
      "Investment Ready",
      "Strong ROI Potential",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime agriculture plot located on main road with excellent visibility and high footfall area. Perfect for farmhouse and agriculture needs.",
    verified: true,
    projectSlug: "",
  },
  {
    id: 10,
    title: "Agriculture Land on Ujjain-Jhalawar Road",
    slug: "agriculture-land-ujjain-jhalawar-road",
    type: "agriculture",
    location: "Ujjain-Jhalawar Road, Madhya Pradesh",
    price: "Call for Price",
    area: "3.75 Beegha",
    coordinates: { lat: 23.40050323534213, lng: 75.86740444907431 },
    image: "/Jhalawar.png",
    features: [
      "Main Road",
      "Highway Access",
      "200 feet front",
      "Investment Ready",
      "Strong ROI Potential",
    ],
    rating: 4.9,
    views: 567,
    description:
      "Prime agriculture plot located on main road with 200 sqft front, excellent visibility and high footfall area. Perfect for farmhouse and agriculture needs.",
    verified: true,
    projectSlug: "",
  },
];

export const projects: Project[] = [
  {
    id: 1,
    slug: "aarna-ssd-enclave",
    title: "Aarna SSD Enclave",
    developer: "Sahu Developers",
    image: "/residence.png",
    images: ["/1407.JPEG", "/1302.png"],
    video: "",
    description:
      "This premier residential project offers luxurious living spaces with state-of-the-art amenities. Located in a prime area with excellent connectivity, it also provides the added convenience of integrated retail shops for all your daily needs.",
    location: "Indore, Madhya Pradesh",
    status: "Under Construction",
    features: [
      "School 6 mins",
      "Hospital 6 mins",
      "Vegetable/Fruits Market",
      "Parking space available",
      "Strong ROI Potential",
      "Lift Access",
    ],
    propertyCount: 6,
  },
];
